### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BuddhiAbeyratne** [reclaim-the-stack/k#9]
Hey guys,
 
The CLI tool doesn't seem to have a license. was this on purpose ?
This is halting us from using the tool at our organisation. 
I would like to suggest MIT but even something similar to TSL should be fine I think 

_Moved down to keep the issue clean._
The blog has been very insightful and helped us gain an understanding on concenses of others on similar uses we were facing (eg: PGO vs CNPG )Talos Manager seems like a fun project but we decided to use an OpenToFu based method to build our cluster (We think Talos is good but to prevent vendor issues we decided on rolling our own locked down version of microOS (We've done this before and have our scripts already modified, would not recommend otherwise))
We'd like to use the Get Started project too but we are yet jump the gun on it. However if we do we would want to use it with the CLI helper. 

Thanks in advance.

**Comment by dbackeus** [comment]
Thanks for pointing this out!

Fixed by adding an MIT license in https://github.com/reclaim-the-stack/k/commit/9536e19db23cb40a83b4511d007e9aa841a37934
